"""empty message

Revision ID: 9eb37de8381c
Revises: 0fc429eb06aa
Create Date: 2021-08-15 20:53:35.995834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb37de8381c'
down_revision = '0fc429eb06aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('image_link', sa.String(), nullable=False))
    op.add_column('Movie', sa.Column('image_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'image_link')
    op.drop_column('Actor', 'image_link')
    # ### end Alembic commands ###
